##build docker pserver
#bash setup_image.sh latest
#or
#bash setup_container.sh latest /path/to/config.json

ARG L4T_VERSION=35.4.1

FROM nvcr.io/nvidia/l4t-base:${L4T_VERSION}

#need to redefine
ARG L4T_VERSION=35.4.1

RUN echo "L4T_VERSION=${L4T_VERSION}"

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    curl \
    git \
    nano \
    pkg-config \
    v4l-utils \
    usbutils \
    network-manager \
    p7zip-full p7zip-rar
ENTRYPOINT ["/bin/bash"]
